FROM mcr.microsoft.com/playwright/python:v1.58.0-noble

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=bugbinder.settings
ENV DJANGO_ALLOW_ASYNC_UNSAFE=1

WORKDIR /app

COPY ./Pipfile ./Pipfile.lock /app/

RUN pip install pipenv && pipenv install --dev --system --deploy \
    && rm -rf /root/.cache/pip

COPY . /app

WORKDIR /app/bugbinder

CMD ["sh", "-c", "python manage.py migrate && pytest"]
